# Generated by Django 6.0.7 on 2026-07-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, help_text='Short player background/description shown on their profile page.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, help_text='Square headshot works best (e.g. 500x500px). Shown on the squad grid and profile page.', null=True, upload_to='players/'),
        ),
    ]
