# Generated by Django 6.0.7 on 2026-07-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_player_bio_alter_player_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(help_text='Which tournament the team is registering for, e.g. "Gurkhali Cup 2026".', max_length=150)),
                ('team_name', models.CharField(max_length=120)),
                ('division', models.CharField(choices=[('OPEN_M', "Open / Men's"), ('WOMENS', "Women's"), ('MIXED', 'Mixed'), ('YOUTH', 'Youth / Junior'), ('MASTERS', 'Masters (35+)'), ('CORP', 'Corporate / Social')], default='OPEN_M', max_length=10)),
                ('manager_name', models.CharField(help_text="Team manager or coach's full name.", max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('player_count', models.PositiveSmallIntegerField(help_text='Estimated number of players in the squad.')),
                ('home_city', models.CharField(blank=True, max_length=120)),
                ('experience', models.TextField(blank=True, help_text='Previous tournament experience, if any (optional).')),
                ('notes', models.TextField(blank=True, help_text='Anything else the organisers should know (optional).')),
                ('agreed_to_rules', models.BooleanField(default=False, help_text='Team confirmed they agree to the tournament rules and code of conduct.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('WAITLIST', 'Waitlisted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
