# Generated by Django 6.0.7 on 2026-07-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_teamregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistration',
            name='player_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Automatically set to the number of named players in the roster below.'),
        ),
        migrations.CreateModel(
            name='RegisteredPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='club.teamregistration')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
