# Generated by Django 6.0.7 on 2026-07-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_teamregistration_player_count_registeredplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live now'), ('FINISHED', 'Finished')], default='SCHEDULED', help_text="Set to 'Live now' on match day to show it at the top of the schedule with a live indicator and score.", max_length=10),
        ),
    ]
