# Generated by Django 6.0.7 on 2026-07-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_match_home_away_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(help_text='Chosen from Approved registrations. Must match a group team name for table sync after the lucky draw.', max_length=120),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(help_text='Chosen from Approved registrations. Must match a group team name for table sync after the lucky draw.', max_length=120),
        ),
    ]
