# Generated by Django 6.0.7 on 2026-07-25 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_match_team_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Which World Cup group table this result updates. Both teams are added to the group automatically when you save.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='club.competitiongroup'),
        ),
    ]
