# Generated by Django 6.0.7 on 2026-07-26 12:52

from django.db import migrations, models


def forwards_normalize_registrations(apps, schema_editor):
    TeamRegistration = apps.get_model("club", "TeamRegistration")
    for reg in TeamRegistration.objects.all():
        changed = False
        if reg.division != "OPEN_7A":
            reg.division = "OPEN_7A"
            changed = True
        if not (reg.tournament_name or "").strip():
            reg.tournament_name = "Dashain Cup 2026"
            changed = True
        if not (reg.home_city or "").strip():
            reg.home_city = "Darwin"
            changed = True
        if not (reg.experience or "").strip():
            reg.experience = "N/A"
            changed = True
        if not (reg.notes or "").strip():
            reg.notes = "N/A"
            changed = True
        if changed:
            reg.save()


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0012_knockoutbracket"),
    ]

    operations = [
        migrations.RunPython(forwards_normalize_registrations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="teamregistration",
            name="division",
            field=models.CharField(
                choices=[("OPEN_7A", "Open 7A-side football competition")],
                default="OPEN_7A",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="teamregistration",
            name="email",
            field=models.EmailField(
                help_text="Must be a valid Gmail address (example@gmail.com).",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="teamregistration",
            name="experience",
            field=models.TextField(help_text="Previous tournament experience (required)."),
        ),
        migrations.AlterField(
            model_name="teamregistration",
            name="home_city",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="teamregistration",
            name="notes",
            field=models.TextField(
                help_text="Anything else the organisers should know (required — write N/A if none)."
            ),
        ),
        migrations.AlterField(
            model_name="teamregistration",
            name="tournament_name",
            field=models.CharField(
                default="Dashain Cup 2026",
                help_text='Fixed for this season — "Dashain Cup 2026".',
                max_length=150,
            ),
        ),
    ]
