# Generated by Django 6.0.7 on 2026-07-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_registration_dashain_cup_roster12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='Club Gmail address used as the visible sender / reply-to for registration emails. Must match EMAIL_HOST_USER in .env (same Gmail), and that account needs a Gmail App Password in EMAIL_HOST_PASSWORD — otherwise emails only print to the server console and never reach inboxes.', max_length=254),
        ),
    ]
